const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

test("desktop login routes through a recoverable first-run onboarding page", () => {
  const main = fs.readFileSync(path.join(__dirname, "..", "main.js"), "utf8");
  const preload = fs.readFileSync(path.join(__dirname, "..", "preload.js"), "utf8");
  const html = fs.readFileSync(path.join(__dirname, "..", "onboarding.html"), "utf8");
  const script = fs.readFileSync(path.join(__dirname, "..", "onboarding.js"), "utf8");
  assert.match(main, /routeAfterAuthentication/);
  assert.match(main, /onboarding\.html/);
  assert.match(main, /isCloudEdition \? "onboarding\.html" : "home\.html"/);
  assert.match(preload, /getOnboarding/);
  assert.match(preload, /completeOnboarding/);
  assert.match(html, /连接对话 AI/);
  assert.match(html, /自定义角色/);
  assert.match(html, /<span>性别<\/span>/);
  assert.match(html, /<option value="女">女<\/option>/);
  assert.match(html, /<option value="男">男<\/option>/);
  assert.match(html, /<option value="中性">中性<\/option>/);
  assert.match(html, /<option value="custom">自定义<\/option>/);
  assert.doesNotMatch(html, /id="assistantDefinition"/);
  assert.doesNotMatch(html, /角色定位/);
  assert.match(html, /id="traitOptions"/);
  assert.match(html, /选择 3～5 个/);
  assert.match(html, /id="traitHint"/);
  assert.match(html, /data-trait="温柔"/);
  assert.match(html, /data-trait="理性"/);
  assert.match(html, /data-trait="元气"/);
  assert.match(html, /data-trait="傲娇"/);
  assert.match(html, /data-trait="天然呆"/);
  assert.match(html, /data-trait="小恶魔"/);
  assert.doesNotMatch(html, /id="assistantTraits"/);
  assert.match(html, /id="relationshipOptions"/);
  assert.match(html, /data-relationship="恋人"/);
  assert.match(html, /data-relationship="青梅竹马"/);
  assert.match(html, /data-relationship="学姐"/);
  assert.match(html, /data-relationship="邻桌姐姐"/);
  assert.match(html, /data-relationship="女仆"/);
  assert.match(html, /data-relationship="管家"/);
  assert.match(html, /data-relationship="custom"/);
  assert.match(html, /id="customRelationshipInput" class="hidden" maxlength="10"/);
  assert.doesNotMatch(html, /data-relationship="守护者"/);
  assert.doesNotMatch(html, /data-relationship="家人"/);
  assert.doesNotMatch(html, /data-relationship="搭档"/);
  assert.doesNotMatch(html, /id="assistantRelationship"/);
  assert.match(html, /id="voiceOptions"/);
  assert.match(html, /data-voice="活泼俏皮"/);
  assert.match(html, /data-voice="偶尔“喵~”"/);
  assert.doesNotMatch(html, /id="assistantVoice"/);
  assert.match(script, /testAIProvider/);
  assert.match(script, /updateAssistantProfile/);
  assert.match(script, /getGenderValue/);
  assert.match(script, /toggleTrait/);
  assert.match(script, /MAX_PRESET_TRAITS = 5/);
  assert.match(script, /MAX_VOICE_STYLES = 4/);
  assert.match(script, /getTraitValues/);
  assert.match(script, /selectedRelationship/);
  assert.match(script, /customRelationshipInput/);
  assert.match(script, /selectedVoiceStyles/);
  assert.match(script, /completeOnboarding/);
});

test("custom companions start from an empty role image baseline", () => {
  const script = fs.readFileSync(path.join(__dirname, "..", "onboarding.js"), "utf8");
  assert.match(script, /state\.choice === "custom"/);
  assert.match(script, /会在相处中逐渐形成个性的数字伙伴/);
  assert.match(script, /avatarDataUrl: "", personaImageDataUrl: ""/);
});
